language: go
go:
  - "1.16"

services:
  - docker

notifications:
  email: false

env:
  - GO111MODULE=on GOTIFY_VERSIONS="v2.0.22 v2.0.21 v2.0.20 v2.0.19 v2.0.18"

before_install:
  - make download-tools
  - go get -d

script:
  - go test ./...
  - >
    for TARGET in $GOTIFY_VERSIONS; do
      make GOTIFY_VERSION="$TARGET" FILE_SUFFIX="-for-gotify-$TARGET" build;
    done

deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: build/*.so
    skip_cleanup: true
    on:
      tags: true
